blank_issues_enabled: false
contact_links:
  - name: Coding Train Discord
    url: https://thecodingtrain.com/discord
    about: Ask questions and get help submitting on the Discord server
  - name: Coding Train Website
    url: https://thecodingtrain.com
    about: Check out the new Coding Train Website!
